### PR TITLE
allow user to remove properties from contact in contact list

### PR DESCRIPTION
**Pull request by ghost**
solves
FIXME: there is a thunderbird bug here which prevent the properties from actually be deleted...

### CODE REVIEW

**Comment by extrafu** [comment]
Does that patch also need to be applied for the TB10 extensions?

**Comment by ghost** [comment]
> Does that patch also need to be applied for the TB10 extensions?

I do not know. I only tested with TB17 and the according version of the plugin.

**Comment by extrafu** [comment]
All set to merge this pull request?

**Comment by ghost** [comment]
Yes, These changes and fixes work just fine for me for several days.

**Comment by ghost** [comment]
Do I have to close this pull request?

**Pull request merged**
